language: ruby

rvm:
  - 2.6.5

cache: bundler

services:
  - postgresql

install: bundler install

before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

before_install:
  - gem update --system
  - gem install bundler -v '1.17.3'

bundler_args: --without production

script:
  - bundle exec rspec
  - bundle exec overcommit --sign
  - bundle exec overcommit --sign pre-commit
  - bundle exec overcommit --run
